spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/realtime_chat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:UZ5V48D3}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key : "6e31ba067628ce5611c70b5318fcf456"

jwt:
  expiration-minutes: 1440

cloudinary:
  cloud-name: dh9gwpfor
  api-key: 829472641856166
  api-secret: c0HMPnv-kHhsIZDeYUEqQDn99w8

app:
  activation:
    master-key: ${CHAT_MASTER_KEY}